$(function() {
        'use strict';
        
    ///英単語から貼り付け/////////////////////////////////////////////
	const words = [
        {en: 'form', ja: '形態'},
        {en: 'research', ja: '[名] 研究'},
        {en: 'author', ja: '著者'},
        {en: 'government', ja: '政府'},
        {en: 'society', ja: '社会'},
        {en: 'passage', ja: '(本などの)一節'},
        {en: 'environment', ja: '<the environmentで>(自然)環境'},
        {en: 'sense', ja: '感覚'},
        {en: 'case', ja: '場合'},
        {en: 'brain', ja: '脳'},
        {en: 'amount', ja: '量'},
        {en: 'effect', ja: '影響'},
        {en: 'population', ja: '人口'},
        {en: 'technology', ja: '(科学)技術'},
        {en: 'product', ja: '製品'},
        {en: 'nation', ja: '国'},
        {en: 'value', ja: '価値'},
        {en: 'process', ja: '過程'},
        {en: 'community', ja: '地域社会'},
        {en: 'force', ja: '力'},
        {en: 'seem', ja: '～のように見える'},
        {en: 'last', ja: '(ある期間)続く'},
        {en: 'cause', ja: '～を引き起こす'},
        {en: 'face', ja: '(建物などが)～に面する'},
        {en: 'create', ja: '～を作り出す'},
        {en: 'let', ja: '<let A doで>Aに(したいように)～させる'},
        {en: 'pay', ja: '(～を)支払う'},
        {en: 'produce', ja: '～を生産[製造]する'},
        {en: 'allow', ja: '<allow A to doで>Aが～するのを許す'},
        {en: 'train', ja: '～を訓練する；訓練を受ける'},
        {en: 'suggest', ja: '～を提案する'},
        {en: 'increase', ja: '増える'},
        {en: 'bear', ja: '～に耐える'},
        {en: 'consider', ja: '～をじっくり考える'},
        {en: 'cost', ja: '(…に)(金額・費用)がかかる'},
        {en: 'realize', ja: '(考えて)～に気づく'},
        {en: 'describe', ja: '～の特徴を述べる'},
        {en: 'protect', ja: '～を保護する'},
        {en: 'offer', ja: '(…に)～を申し出る'},
        {en: 'tend', ja: '<tend to doで>～しがちである'},
        {en: 'following', ja: '<the followingで>次の'},
        {en: 'public', ja: '公共の'},
        {en: 'possible', ja: '(実現)可能な'},
        {en: 'likely', ja: '<be likely to doで>～しそうだ'},
        {en: 'several', ja: 'いくつかの'},
        {en: 'common', ja: 'よくある'},
        {en: 'individual', ja: '個々の'},
        {en: 'modern', ja: '現代の'},
        {en: 'local', ja: '地元の'},
        {en: 'global', ja: '地球(規模)の'},
        {en: 'moment', ja: '<a momentで>一瞬'},
        {en: 'ability', ja: '能力'},
        {en: 'issue', ja: '問題(点)'},
        {en: 'cell', ja: '細胞'},
        {en: 'species', ja: '(生物学上の)種'},
        {en: 'situation', ja: '状況'},
        {en: 'period', ja: '期間'},
        {en: 'condition', ja: '(物の)状態'},
        {en: 'method', ja: '(組織的な)方法'},
        {en: 'base', ja: '土台'},
        {en: 'meaning', ja: '意味'},
        {en: 'lie', ja: 'うそ'},
        {en: 'attention', ja: '注意'},
        {en: 'project', ja: '事業計画'},
        {en: 'rate', ja: '割合'},
        {en: 'service', ja: '(公共の)事業'},
        {en: 'knowledge', ja: '知識'},
        {en: 'influence', ja: '影響'},
        {en: 'theory', ja: '(学)説'},
        {en: 'interest', ja: '興味'},
        {en: 'stress', ja: '～を強調する'},
        {en: 'discover', ja: '～を発見する'},
        {en: 'include', ja: '(全体の一部として)～を含む'},
        {en: 'claim', ja: '～を主張する'},
        {en: 'lie', ja: '横になる'},
        {en: 'remain', ja: '～のままである'},
        {en: 'provide', ja: '～を提供する'},
        {en: 'avoid', ja: '(望ましくないこと)を避ける'},
        {en: 'notice', ja: '(見たり聞いたりして)～に気づく'},
        {en: 'accept', ja: '～を受け入れる'},
        {en: 'improve', ja: '～を改善する'},
        {en: 'fail', ja: '<fail to doで>～しそこなう'},
        {en: 'approach', ja: '～に近づく'},
        {en: 'affect', ja: '～に影響を及ぼす'},
        {en: 'design', ja: '～を設計する'},
        {en: 'express', ja: '(感情・考えなど)を表現する'},
        {en: 'depend', ja: '<depend on Aで>A次第である'},
        {en: 'occur', ja: '(出来事が)起こる'},
        {en: 'argue', ja: '口論する'},
        {en: 'recognize', ja: '(前から知っている人・物)だとわかる'},
        {en: 'similar', ja: 'よく似た'},
        {en: 'certain', ja: '<be certainで>確信している'},
        {en: 'average', ja: '平均の'},
        {en: 'major', ja: '(同種のものと比べて)大きな'},
        {en: 'particular', ja: '特定の'},
        {en: 'present', ja: '出席して'},
        {en: 'physical', ja: '身体の'},
        {en: 'cultural', ja: '文化の'},
        {en: 'recent', ja: '最近の'},
        {en: 'complete', ja: '完全な'},
        {en: 'disease', ja: '病気'},
        {en: 'experiment', ja: '実験'},
        {en: 'benefit', ja: '利益'},
        {en: 'record', ja: '記録'},
        {en: 'role', ja: '役割'},
        {en: 'object', ja: '物体'},
        {en: 'growth', ja: '増加'},
        {en: 'event', ja: '(重要な)出来事'},
        {en: 'memory', ja: '記憶(力)'},
        {en: 'effort', ja: '努力'},
        {en: 'skill', ja: '技能'},
        {en: 'survey', ja: '調査'},
        {en: 'choice', ja: '選択'},
        {en: 'economy', ja: '経済'},
        {en: 'relationship', ja: '関係'},
        {en: 'sentence', ja: '文'},
        {en: 'opportunity', ja: '機会'},
        {en: 'model', ja: '手本'},
        {en: 'fear', ja: '恐れ'},
        {en: 'death', ja: '死'},
        {en: 'guess', ja: '～を推測する'},
        {en: 'prepare', ja: '～を準備する'},
        {en: 'develop', ja: '～を発展[発達]させる；発展[発達]する'},
        {en: 'solve', ja: '～を解決する'},
        {en: 'encourage', ja: '～を励ます'},
        {en: 'expect', ja: '～を予想[予期]する'},
        {en: 'deal', ja: '<deal with Aで>A[問題など]を処理する'},
        {en: 'measure', ja: '(大きさ・量・速さなど)を測る'},
        {en: 'demand', ja: '～を要求する'},
        {en: 'contain', ja: '(容器・本などが)～を含む'},
        {en: 'various', ja: 'さまざまな'},
        {en: 'political', ja: '政治(上)の'},
        {en: 'scientific', ja: '科学の'},
        {en: 'medical', ja: '医学の'},
        {en: 'whole', ja: '<the wholeで>全体の'},
        {en: 'serious', ja: '深刻な'},
        {en: 'single', ja: '<a singleで>たった1つの'},
        {en: 'general', ja: '一般的な'},
        {en: 'total', ja: '総計の'},
        {en: 'necessary', ja: '必要な'},
        {en: 'material', ja: '材料'},
        {en: 'lack', ja: '不足'},
        {en: 'decision', ja: '決定'},
        {en: 'source', ja: ' (物・事の)源'},
        {en: 'risk', ja: '危険(性)'},
        {en: 'bill', ja: '請求書'},
        {en: 'professor', ja: '(大学の)教授'},
        {en: 'diet', ja: '(日常の)食事'},
        {en: 'quality', ja: '質'},
        {en: 'data', ja: 'データ'},
        {en: 'note', ja: 'メモ'},
        {en: 'challenge', ja: '難題'},
        {en: 'function', ja: '機能'},
        {en: 'article', ja: '記事'},
        {en: 'shape', ja: '形'},
        {en: 'middle', ja: '<the middleで>中央'},
        {en: 'goal', ja: '目標'},
        {en: 'image', ja: 'イメージ'},
        {en: 'figure', ja: '数値'},
        {en: 'decade', ja: '10年間'},
        {en: 'exist', ja: '存在する'},
        {en: 'reduce', ja: '(数量・程度など)を減らす'},
        {en: 'gain', ja: '～を得る'},
        {en: 'require', ja: '～を必要とする'},
        {en: 'prove', ja: '～を証明する'},
        {en: 'prevent', ja: '<prevent A from doingで>Aが～するのを妨げる'},
        {en: 'compare', ja: '<compare A with[to] Bで>AをBと比較する'},
        {en: 'adapt', ja: '～を適合させる'},
        {en: 'conduct', ja: '～を行う'},
        {en: 'prefer', ja: '<prefer A to Bで>BよりAが好きである'},
        {en: 'successful', ja: '成功した'},
        {en: 'due', ja: '<due to Aで>Aが原因で'},
        {en: 'available', ja: '利用できる'},
        {en: 'western', ja: '<Westernで>西洋の'},
        {en: 'personal', ja: '個人の'},
        {en: 'ancient', ja: '古代の'},
        {en: 'used', ja: '<be used to Aで>Aに慣れている'},
        {en: 'native', ja: '出生地の'},
        {en: 'daily', ja: '毎日の'},
        {en: 'correct', ja: '正しい'},
        {en: 'generation', ja: '世代 (注) 同じ時代に属する人々。'},
        {en: 'movement', ja: '(政治的・社会的な)運動'},
        {en: 'statement', ja: '声明'},
        {en: 'means', ja: '手段'},
        {en: 'expert', ja: '専門家'},
        {en: 'intelligence', ja: '知能'},
        {en: 'stage', ja: '(変化・発展の)段階'},
        {en: 'variety', ja: '<a variety of Aで>いろいろなA'},
        {en: 'industry', ja: '産業'},
        {en: 'patient', ja: '患者'},
        {en: 'conversation', ja: '会話'},
        {en: 'clothes', ja: '服'},
        {en: 'pressure', ja: '(社会的な)圧力'},
        {en: 'position', ja: '位置'},
        {en: 'degree', ja: '(温度・角度などの)度'},
        {en: 'range', ja: '範囲'},
        {en: 'access', ja: '(場所への)接近(方法)'},
        {en: 'importance', ja: '重要性'},
        {en: 'neighbor', ja: '隣人'},
        {en: 'policy', ja: '政策'},
        {en: 'indicate', ja: '(調査などが)～を示す'},
        {en: 'refer', ja: '<refer to Aで>Aに言及する'},
        {en: 'manage', ja: '～を経営する'},
        {en: 'focus', ja: '(注意・意識など)を集中させる'},
        {en: 'promote', ja: '～を促進する'},
        {en: 'observe', ja: '～を観察する'},
        {en: 'raise', ja: '(物・料金など)を上げる'},
        {en: 'maintain', ja: '～を維持する'},
        {en: 'search', ja: '(場所など)を捜す'},
        {en: 'discuss', ja: '～について話し合う'},
        {en: 'media', ja: '<the (mass) mediaで>(マス)メディア'},
        {en: 'factor', ja: '要因'},
        {en: 'distance', ja: '距離'},
        {en: 'standard', ja: '水準'},
        {en: 'volunteer', ja: 'ボランティア'},
        {en: 'resource', ja: '<resourcesで>資源'},
        {en: 'customer', ja: '(商店・企業などの)顧客'},
        {en: 'strategy', ja: '戦略'},
        {en: 'region', ja: '(広大な)地域'},
        {en: 'evidence', ja: '証拠'},
        {en: 'according', ja: '<according to Aで>Aによれば'},
        {en: 'rather', ja: '<A rather than Bで>BよりもむしろA'},
        {en: 'probably', ja: 'たぶん'},
        {en: 'perhaps', ja: 'ひょっとすると'},
        {en: 'instead', ja: '(その)代わりに'},
        {en: 'especially', ja: '特に'},
        {en: 'simply', ja: '単に'},
        {en: 'therefore', ja: 'それゆえ'},
        {en: 'thus', ja: 'したがって'},
        {en: 'indeed', ja: '本当に'},
        {en: 'exactly', ja: '正確に'},
        {en: 'nearly', ja: 'ほとんど'},
        {en: 'further', ja: '(程度が)さらに'},
        {en: 'immediately', ja: 'すぐに'},
        {en: 'forward', ja: '前へ'},
        {en: 'extremely', ja: '極めて'},
        {en: 'eventually', ja: '結局は'},
        {en: 'hardly', ja: 'ほとんど～ない'},
        {en: 'ahead', ja: '(位置的に)前方に[を]'},
        {en: 'highly', ja: '高度に'},
        {en: 'within', ja: '[前] (時間・距離が)～以内に'},
        {en: 'per', ja: '[前] ～につき'},
        {en: 'including', ja: '[前] ～を含めて'},
        {en: 'throughout', ja: '[前] ～の間ずっと'},
        {en: 'despite', ja: '[前] ～にもかかわらず'},
        {en: 'beyond', ja: '[前] ～の向こうに'},
        {en: 'except', ja: '[前] ～を除いて (＝except for)'},
        {en: 'whether', ja: '[接] ～かどうか'},
        {en: 'provided', ja: '[接] もし～ならば'},
        {en: 'unless', ja: '[接] ～でない[しない]限り'},
        {en: 'difficulty', ja: '苦労'},
        {en: 'climate', ja: '(一地域の年間を通じた)気候'},
        {en: 'belief', ja: '確信'},
        {en: 'contrast', ja: '対照'},
        {en: 'blood', ja: '血'},
        {en: 'progress', ja: '進歩'},
        {en: 'damage', ja: '損害'},
        {en: 'item', ja: '項目'},
        {en: 'concept', ja: '概念'},
        {en: 'task', ja: '(やるべき)仕事'},
        {en: 'surface', ja: '表面'},
        {en: 'sale', ja: '販売'},
        {en: 'income', ja: '(定期的な)収入'},
        {en: 'habit', ja: '(個人の)習慣'},
        {en: 'account', ja: '報告'},
        {en: 'danger', ja: '危険'},
        {en: 'freedom', ja: '(権利としての)自由'},
        {en: 'aspect', ja: '(物事の)一面'},
        {en: 'loss', ja: '失うこと'},
        {en: 'mass', ja: '<a mass of Aで>大量のA'},
        {en: 'decline', ja: '減少する'},
        {en: 'replace', ja: '～に取って代わる'},
        {en: 'spread', ja: '広まる；～を広める'},
        {en: 'waste', ja: '～をむだに使う'},
        {en: 'supply', ja: '～に[を]供給する'},
        {en: 'mention', ja: '～に(ついて)言及する'},
        {en: 'survive', ja: '～を生き延びる；生き残る'},
        {en: 'add', ja: '(～を)加える'},
        {en: 'separate', ja: '～を隔てる'},
        {en: 'serve', ja: '～に(飲食物)を出す'},
        {en: 'regard', ja: '<regard A as Bで>AをBとみなす'},
        {en: 'decrease', ja: '減る'},
        {en: 'perform', ja: '～を上演する'},
        {en: 'attend', ja: '(会議など)に出席する'},
        {en: 'achieve', ja: '～を達成する'},
        {en: 'promise', ja: '(～を)約束する'},
        {en: 'connect', ja: '<connect A to[with] Bで>AをBにつなぐ'},
        {en: 'count', ja: '(～を)数える'},
        {en: 'attract', ja: '(興味・注意など)を引きつける'},
        {en: 'doubt', ja: '～を疑う'},
        {en: 'concerned', ja: '<be concernedで>心配している'},
        {en: 'official', ja: '公式の'},
        {en: 'appropriate', ja: '適切な'},
        {en: 'female', ja: '女性の'},
        {en: 'fresh', ja: '新鮮な'},
        {en: 'powerful', ja: '影響力のある'},
        {en: 'familiar', ja: 'よく知られた'},
        {en: 'ordinary', ja: '普通の'},
        {en: 'wild', ja: '野生の'},
        {en: 'fat', ja: '太っている'},
        {en: 'technique', ja: '(専門)技術'},
        {en: 'phrase', ja: '成句'},
        {en: 'advantage', ja: '利点'},
        {en: 'character', ja: '性格'},
        {en: 'gas', ja: '(燃料用の)ガス'},
        {en: 'citizen', ja: '市民'},
        {en: 'truth', ja: '<the truthで>真実'},
        {en: 'percentage', ja: 'パーセント'},
        {en: 'explanation', ja: '説明'},
        {en: 'instance', ja: '例'},
        {en: 'mark', ja: '印'},
        {en: 'pollution', ja: '汚染'},
        {en: 'feature', ja: '特徴'},
        {en: 'trade', ja: '貿易'},
        {en: 'tool', ja: '道具'},
        {en: 'sort', ja: '種類'},
        {en: 'atmosphere', ja: '雰囲気'},
        {en: 'impact', ja: '影響'},
        {en: 'attitude', ja: '態度'},
        {en: 'crowd', ja: '群衆'},
        {en: 'disappear', ja: '姿を消す'},
        {en: 'define', ja: '～を定義する'},
        {en: 'reflect', ja: '(光など)を反射する'},
        {en: 'contribute', ja: '貢献する'},
        {en: 'represent', ja: '～を代表する'},
        {en: 'match', ja: '～に合う'},
        {en: 'exchange', ja: '～を交換する'},
        {en: 'confuse', ja: '～を困惑させる'},
        {en: 'respond', ja: '反応する'},
        {en: 'treat', ja: '～を扱う'},
        {en: 'male', ja: '男性の'},
        {en: 'huge', ja: '(大きさが)巨大な'},
        {en: 'professional', ja: 'プロの'},
        {en: 'essential', ja: '必要不可欠な'},
        {en: 'current', ja: '現在の'},
        {en: 'positive', ja: '前向きな'},
        {en: 'chemical', ja: '化学の'},
        {en: 'comfortable', ja: '快適な'},
        {en: 'central', ja: '中央の'},
        {en: 'negative', ja: '悪い'},
        {en: 'coal', ja: '石炭'},
        {en: 'gene', ja: '遺伝子'},
        {en: 'traffic', ja: '交通(量)'},
        {en: 'reality', ja: '現実'},
        {en: 'happiness', ja: '幸福'},
        {en: 'balance', ja: 'バランス'},
        {en: 'universe', ja: '<the universeで>宇宙'},
        {en: 'factory', ja: '工場'},
        {en: 'muscle', ja: '筋肉'},
        {en: 'audience', ja: '(劇・映画などの)観客'},
        {en: 'cycle', ja: '循環'},
        {en: 'electricity', ja: '電気'},
        {en: 'link', ja: 'つながり'},
        {en: 'cancer', ja: 'がん'},
        {en: 'contact', ja: '連絡'},
        {en: 'favor', ja: '支持'},
        {en: 'career', ja: '職業'},
        {en: 'majority', ja: '(ある集団の)大多数'},
        {en: 'officer', ja: '役人'},
        {en: 'democracy', ja: '民主主義'},
        {en: 'reply', ja: '返事をする'},
        {en: 'involve', ja: '(必然的に)～を伴う'},
        {en: 'press', ja: '～を押す'},
        {en: 'feed', ja: '(動物など)にえさ[食べ物]をやる'},
        {en: 'suffer', ja: '<suffer from Aで>A[病気]を患う'},
        {en: 'organize', ja: '(行事・活動など)を準備[計画]する'},
        {en: 'succeed', ja: '成功する'},
        {en: 'destroy', ja: '～を破壊する'},
        {en: 'appreciate', ja: '～に感謝する'},
        {en: 'identify', ja: '～を(同一の人[物]だと)確認する'},
        {en: 'worried', ja: '<be worriedで>心配している'},
        {en: 'complicated', ja: '複雑な'},
        {en: 'unique', ja: '類まれな'},
        {en: 'mental', ja: '精神の'},
        {en: 'significant', ja: '重大な'},
        {en: 'responsible', ja: '<be responsible for Aで>Aに責任がある'},
        {en: 'blank', ja: '空白の'},
        {en: 'private', ja: '私的な'},
        {en: 'extra', ja: '余分の'},
        {en: 'entire', ja: '全体の'},
        {en: 'novel', ja: '(長編)小説'},
        {en: 'series', ja: '<a series of Aで>一連のA'},
        {en: 'stranger', ja: '見知らぬ人'},
        {en: 'section', ja: '(分けられた)区分'},
        {en: 'principle', ja: '主義'},
        {en: 'popularity', ja: '人気'},
        {en: 'conflict', ja: '対立'},
        {en: 'anger', ja: '怒り'},
        {en: 'satellite', ja: '人工衛星 (＝artificial satellite)'},
        {en: 'emotion', ja: '感情'},
        {en: 'department', ja: '(会社などの)部門'},
        {en: 'poverty', ja: '貧困'},
        {en: 'structure', ja: '構造'},
        {en: 'insect', ja: '虫'},
        {en: 'revolution', ja: '(政治的)革命'},
        {en: 'safety', ja: '安全'},
        {en: 'creature', ja: '生き物'},
        {en: 'content', ja: '<contentsで>(容器などの)中身'},
        {en: 'limit', ja: '制限'},
        {en: 'target', ja: '(非難・攻撃などの)標的'},
        {en: 'divide', ja: '～を分ける'},
        {en: 'complain', ja: '不平を言う'},
        {en: 'remove', ja: '～を取り去る'},
        {en: 'bite', ja: '～をかむ'},
        {en: 'examine', ja: '～を調べる'},
        {en: 'score', ja: '(得点)を取る；得点する'},
        {en: 'seek', ja: '(答え・仕事など)を探す'},
        {en: 'ignore', ja: '～を無視する'},
        {en: 'attempt', ja: '～を試みる'},
        {en: 'invent', ja: '～を発明する'},
        {en: 'double', ja: '2倍の'},
        {en: 'complex', ja: '複雑な'},
        {en: 'mobile', ja: '移動式の'},
        {en: 'specific', ja: '特定の'},
        {en: 'normal', ja: '標準の'},
        {en: 'aware', ja: '<be awareで>気づいている'},
        {en: 'regular', ja: '規則的な'},
        {en: 'obvious', ja: '明らかな'},
        {en: 'active', ja: '活動的な'},
        {en: 'characteristic', ja: '特有の'},
        {en: 'profit', ja: '利益'},
        {en: 'association', ja: '(同業者などの)協会'},
        {en: 'detail', ja: '細部'},
        {en: 'drug', ja: '麻薬'},
        {en: 'device', ja: '装置'},
        {en: 'trust', ja: '信頼'},
        {en: 'dot', ja: '点'},
        {en: 'owner', ja: '所有者'},
        {en: 'immigrant', ja: '(外国からの)移民'},
        {en: 'excuse', ja: '言い訳'},
        {en: 'prize', ja: '賞'},
        {en: 'shock', ja: 'ショック'},
        {en: 'trend', ja: '傾向'},
        {en: 'track', ja: '(踏みならされてできた)小道'},
        {en: 'term', ja: '(専門)用語'},
        {en: 'authority', ja: '権威'},
        {en: 'household', ja: '家族'},
        {en: 'luck', ja: '運'},
        {en: 'code', ja: '規定'},
        {en: 'fuel', ja: '燃料'},
        {en: 'release', ja: '～を解き放す'},
        {en: 'tie', ja: '(ひもなどで)～を結びつける'},
        {en: 'reveal', ja: '～を明らかにする'},
        {en: 'conclude', ja: '～と結論づける'},
        {en: 'assume', ja: '～と思い込む'},
        {en: 'escape', ja: '逃げる'},
        {en: 'demonstrate', ja: '～を論証する'},
        {en: 'participate', ja: '参加する'},
        {en: 'publish', ja: '～を出版する'},
        {en: 'hang', ja: '(絵・服など)を掛ける；(絵・服などが)掛っている'},
        {en: 'previous', ja: '(時間・順序が)前の'},
        {en: 'equal', ja: '(数量・度合などが)等しい'},
        {en: 'direct', ja: '直接の'},
        {en: 'nervous', ja: '緊張して'},
        {en: 'suitable', ja: '適した'},
        {en: 'ill', ja: '病気で'},
        {en: 'fair', ja: '適正な'},
        {en: 'potential', ja: '潜在的な'},
        {en: 'unable', ja: '<be unable to doで>～することができない'},
        {en: 'tiny', ja: 'とても小さい'},
        {en: 'tradition', ja: '伝統'},
        {en: 'crop', ja: '(農)作物'},
        {en: 'debate', ja: '討論'},
        {en: 'fashion', ja: '流行'},
        {en: 'bone', ja: '骨'},
        {en: 'relative', ja: '親せき'},
        {en: 'consequence', ja: '結果'},
        {en: 'childhood', ja: '子ども時代'},
        {en: 'storm', ja: '嵐'},
        {en: 'block', ja: 'ブロック'},
        {en: 'refuse', ja: '～を断る'},
        {en: 'lay', ja: '～を置く'},
        {en: 'suppose', ja: '～であろうと思う'},
        {en: 'insist', ja: '(～を)主張する'},
        {en: 'relax', ja: 'くつろぐ；～をくつろがせる'},
        {en: 'direct', ja: '(言葉・感情・関心など)を向ける'},
        {en: 'judge', ja: '(～を)判断する'},
        {en: 'recall', ja: '～を思い出す'},
        {en: 'repair', ja: '～を修理する'},
        {en: 'predict', ja: '～を予測する'},
        {en: 'gradually', ja: '徐々に'},
        {en: 'somewhere', ja: 'どこかで[に'},
        {en: 'increasingly', ja: 'ますます'},
        {en: 'relatively', ja: '比較的'},
        {en: 'frequently', ja: '頻繁に'},
        {en: 'otherwise', ja: 'そうしないと'},
        {en: 'closely', ja: '密接に'},
        {en: 'slightly', ja: '(量・程度が)わずかに'},
        {en: 'twice', ja: '2度'},
        {en: 'rapidly', ja: '(変化・動きなどが)急速に'},
        {en: 'opposite', ja: '[前] ～の向かい(側)に'},
        {en: 'worth', ja: '[前] ～の価値がある'},
        {en: 'unlike', ja: '[前] ～と違って'},
        {en: 'besides', ja: '[前] ～のほかに'},
        {en: 'beside', ja: '[前] ～のそばに'},
        {en: 'considering', ja: '[前] ～を考慮すると'},
        {en: 'concerning', ja: '[前] ～に関して(の)'},
        {en: 'beneath', ja: '[前] ～の下に[の]'},
        {en: 'whenever', ja: '[接] ～するときはいつ(で)も'},
        {en: 'whereas', ja: '[接] (その)一方で～'},
        {en: 'president', ja: '大統領'},
        {en: 'painting', ja: '絵画'},
        {en: 'origin', ja: '起源'},
        {en: 'manner', ja: 'やり方'},
        {en: 'desire', ja: '欲望'},
        {en: 'aid', ja: '援助'},
        {en: 'sight', ja: '見ること'},
        {en: 'strength', ja: '力'},
        {en: 'talent', ja: '(生まれつきの)才能'},
        {en: 'court', ja: '法廷'},
        {en: 'birth', ja: '誕生'},
        {en: 'labor', ja: '(肉体的な)労働'},
        {en: 'scale', ja: '規模'},
        {en: 'comment', ja: '見解'},
        {en: 'spite', ja: '<in spite of Aで>Aにもかかわらず'},
        {en: 'basis', ja: '(知識・考えなどの)基礎'},
        {en: 'document', ja: '文書'},
        {en: 'staff', ja: '職員'},
        {en: 'pleasure', ja: '楽しみ'},
        {en: 'appearance', ja: '出現'},
        {en: 'regret', ja: '～を後悔する'},
        {en: 'enable', ja: '<enable A to doで>Aが～するのを可能にする'},
        {en: 'rely', ja: '<rely on Aで>Aを頼りにする'},
        {en: 'graduate', ja: '卒業する'},
        {en: 'rush', ja: '大急ぎで行く'},
        {en: 'flow', ja: '(液体・気体が)流れる'},
        {en: 'shift', ja: '(視線・位置など)を移す'},
        {en: 'determine', ja: '～を特定する'},
        {en: 'expand', ja: '(～を)拡大[拡張]する'},
        {en: 'aim', ja: '<aim at Aで>Aを目指す'},
        {en: 'earn', ja: '(金)を稼ぐ'},
        {en: 'obtain', ja: '～を入手する'},
        {en: 'encounter', ja: '～に直面する'},
        {en: 'import', ja: '～を輸入する'},
        {en: 'strike', ja: '～にぶつかる；～をぶつける'},
        {en: 'emerge', ja: '(人・物が)現れる'},
        {en: 'apply', ja: '<apply for Aで>Aを申し込む'},
        {en: 'pat', ja: '(人・動物の体の一部)を軽くたたく'},
        {en: 'adopt', ja: '(方法・計画など)を採用する'},
        {en: 'gather', ja: '集まる；～を集める'},
        {en: 'terrible', ja: 'ひどい'},
        {en: 'typical', ja: '典型的な'},
        {en: 'convenient', ja: '都合のよい'},
        {en: 'independent', ja: '独立した'},
        {en: 'asleep', ja: '眠って'},
        {en: 'practical', ja: '現実的な'},
        {en: 'engaged', ja: '<be engaged in Aで>Aに従事している'},
        {en: 'false', ja: '(情報などが)間違った'},
        {en: 'disappointed', ja: '<be disappointedで>がっかりする'},
        {en: 'primary', ja: '第一の'},
        {en: 'status', ja: '地位'},
        {en: 'crime', ja: '犯罪'},
        {en: 'spot', ja: '場所'},
        {en: 'union', ja: '(労働)組合'},
        {en: 'grade', ja: '学年'},
        {en: 'pain', ja: '(肉体的な)痛み'},
        {en: 'desert', ja: '砂漠'},
        {en: 'path', ja: '(小)道'},
        {en: 'employee', ja: '従業員'},
        {en: 'disaster', ja: '災害'},
        {en: 'coast', ja: '海岸'},
        {en: 'instrument', ja: '器具'},
        {en: 'entrance', ja: '入り口'},
        {en: 'clerk', ja: '店員'},
        {en: 'error', ja: '間違い'},
        {en: 'sheet', ja: '<a sheet of Aで>1枚のA'},
        {en: 'unit', ja: '(全体を構成する)単位'},
        {en: 'vote', ja: '票'},
        {en: 'essay', ja: '(学生の)レポート'},
        {en: 'custom', ja: '(社会的な)慣習'},
        {en: 'charge', ja: '(～に)(料金)を請求する'},
        {en: 'settle', ja: '～を解決する'},
        {en: 'admire', ja: '～を賞賛する'},
        {en: 'compete', ja: '競争する'},
        {en: 'hide', ja: '～を隠す；隠れる'},
        {en: 'concentrate', ja: '(精神を)集中する'},
        {en: 'upset', ja: '～を動揺させる'},
        {en: 'relieve', ja: '(不安・苦痛など)を和らげる'},
        {en: 'blow', ja: '(風が)吹く'},
        {en: 'remind', ja: '<remind A of[about] Bで>AにBを思い出させる'},
        {en: 'behave', ja: 'ふるまう'},
        {en: 'bother', ja: '～を悩ませる'},
        {en: 'admit', ja: '(真実・誤りなどを)を認める'},
        {en: 'bow', ja: 'おじぎをする'},
        {en: 'delay', ja: '～を遅らせる'},
        {en: 'advance', ja: '進む'},
        {en: 'preserve', ja: '～を保存する'},
        {en: 'appeal', ja: '懇願する'},
        {en: 'display', ja: '～を展示する'},
        {en: 'ban', ja: '～を禁止する'},
        {en: 'accurate', ja: '(情報などが)正確な'},
        {en: 'military', ja: '軍(事)の'},
        {en: 'usual', ja: 'いつもの'},
        {en: 'financial', ja: '財政上の'},
        {en: 'calm', ja: '落ち着いた'},
        {en: 'alternative', ja: '代わりの'},
        {en: 'former', ja: '(時間的に)前の'},
        {en: 'thick', ja: '(物が)厚い'},
        {en: 'commercial', ja: '商業の'},
        {en: 'equivalent', ja: '同等の'},
        {en: 'row', ja: '(主に横の)列'},
        {en: 'passenger', ja: '(列車・バス・飛行機などの)乗客'},
        {en: 'poison', ja: '毒'},
        {en: 'journey', ja: '(長い)旅行'},
        {en: 'confidence', ja: '信頼'},
        {en: 'threat', ja: '脅威'},
        {en: 'channel', ja: '海峡'},
        {en: 'violence', ja: '暴力(行為)'},
        {en: 'earthquake', ja: '地震'},
        {en: 'evolution', ja: '(生物の)進化'},
        {en: 'pace', ja: '速度'},
        {en: 'plenty', ja: '<plenty of Aで>たくさんのA'},
        {en: 'logic', ja: '論理'},
        {en: 'tourism', ja: '観光(事業)'},
        {en: 'marriage', ja: '結婚(生活)'},
        {en: 'occasion', ja: '(ある特定の)時'},
        {en: 'impression', ja: '印象'},
        {en: 'destination', ja: '目的地'},
        {en: 'credit', ja: '信用'},
        {en: 'element', ja: '要素'},
        {en: 'intend', ja: '<intend to doで>～するつもりである'},
        {en: 'belong', ja: '<belong to Aで>Aのもの[所有物]である'},
        {en: 'afford', ja: '<can afford to doで>～する(金銭的な)余裕がある'},
        {en: 'grant', ja: '(要求など)を聞き入れる'},
        {en: 'locate', ja: '<be locatedで>位置する'},
        {en: 'cross', ja: '(～を)横切る'},
        {en: 'employ', ja: '～を雇う'},
        {en: 'stick', ja: '～をはりつける；はりつく'},
        {en: 'hate', ja: '～をひどく嫌う'},
        {en: 'reserve', ja: '(席・部屋など)を予約する'},
        {en: 'wealthy', ja: '裕福な'},
        {en: 'tough', ja: '困難な'},
        {en: 'universal', ja: '世界共通の'},
        {en: 'academic', ja: '学問の'},
        {en: 'honest', ja: '正直な'},
        {en: 'overall', ja: '全体の'},
        {en: 'urban', ja: '都市の'},
        {en: 'broad', ja: '(幅の)広い'},
        {en: 'efficient', ja: '効率的な'},
        {en: 'proud', ja: '誇りに思って'},
        {en: 'spirit', ja: '心'},
        {en: 'arrow', ja: '矢'},
        {en: 'equipment', ja: '装置'},
        {en: 'edge', ja: '(物・場所などの)端'},
        {en: 'board', ja: '板'},
        {en: 'athlete', ja: '運動選手'},
        {en: 'harm', ja: '害'},
        {en: 'background', ja: '経歴'},
        {en: 'gap', ja: 'すき間'},
        {en: 'root', ja: '<the rootで>(問題などの)根源'},
        {en: 'youth', ja: '若いころ'},
        {en: 'phenomenon', ja: '現象'},
        {en: 'proportion', ja: '割合'},
        {en: 'moral', ja: '<moralsで>道徳'},
        {en: 'extent', ja: '程度'},
        {en: 'mammal', ja: '哺乳動物'},
        {en: 'thought', ja: '考え'},
        {en: 'context', ja: '(事件・情報などの)背景'},
        {en: 'lecture', ja: '講義'},
        {en: 'colleague', ja: '(職場の)同僚'},
        {en: 'react', ja: '反応する'},
        {en: 'arrange', ja: '～の手はずを整える'},
        {en: 'launch', ja: '～を開始する'},
        {en: 'struggle', ja: '奮闘する'},
        {en: 'announce', ja: '～を発表する'},
        {en: 'lock', ja: '～にかぎをかける'},
        {en: 'consist', ja: '<consist of Aで>Aから成る'},
        {en: 'consume', ja: '～を消費する'},
        {en: 'weigh', ja: '～の重さがある'},
        {en: 'acquire', ja: '(財産・権利・資格など)を得る'},
        {en: 'rare', ja: 'まれな'},
        {en: 'southern', ja: '南の'},
        {en: 'willing', ja: '<be willing to doで>～する気[意思]がある'},
        {en: 'empty', ja: '(容器などが)空の'},
        {en: 'vast', ja: '広大な'},
        {en: 'constant', ja: '絶え間ない'},
        {en: 'ideal', ja: '理想的な'},
        {en: 'domestic', ja: '国内の'},
        {en: 'legal', ja: '合法的な'},
        {en: 'ecological', ja: '環境に優しい'},
        {en: 'flavor', ja: '(味と香りを含めた)風味'},
        {en: 'conference', ja: '(大規模な公式の)会議'},
        {en: 'circumstance', ja: '<circumstancesで>事情'},
        {en: 'signal', ja: '合図'},
        {en: 'quantity', ja: '量'},
        {en: 'liquid', ja: '液体'},
        {en: 'breath', ja: '息'},
        {en: 'scholarship', ja: '奨学金'},
        {en: 'ancestor', ja: '祖先'},
        {en: 'soil', ja: '土'},
        {en: 'bar', ja: '棒'},
        {en: 'finding', ja: '<findingsで>発見(物)'},
        {en: 'religion', ja: '宗教'},
        {en: 'journal', ja: '専門誌'},
        {en: 'metal', ja: '金属'},
        {en: 'vehicle', ja: '乗り物'},
        {en: 'campaign', ja: '(政治的・社会的な)運動'},
        {en: 'stream', ja: '小川'},
        {en: 'bottom', ja: '<the bottomで>一番下'},
        {en: 'frame', ja: '(窓などの)枠'},
        {en: 'handle', ja: '(問題など)を処理する'},
        {en: 'transport', ja: '～を輸送する'},
        {en: 'purchase', ja: '(大きな物・高額な物)を買う'},
        {en: 'recommend', ja: '～を勧める'},
        {en: 'educate', ja: '～を教育する'},
        {en: 'stare', ja: '(驚き・恐れなどで)(～を)じっと見る'},
        {en: 'roll', ja: '転がる；～を転がす'},
        {en: 'arise', ja: '(問題・疑問などが)生じる'},
        {en: 'vary', ja: '(相互に)異なる'},
        {en: 'celebrate', ja: '～を祝う'},
        {en: 'widespread', ja: '広範囲に渡る'},
        {en: 'silent', ja: '黙った'},
        {en: 'thin', ja: '(物が)薄い'},
        {en: 'fundamental', ja: '基本的な'},
        {en: 'loud', ja: '(声が)大きい'},
        {en: 'medium', ja: '(大きさ・量・程度などが)中位の'},
        {en: 'conscious', ja: '<be consciousで>気づいている'},
        {en: 'annual', ja: '1年間の'},
        {en: 'excellent', ja: '優れた'},
        {en: 'enormous', ja: '非常に大きな'},
        {en: 'reject', ja: '～を拒否する'},
        {en: 'establish', ja: '(会社・学校など)を設立する'},
        {en: 'steal', ja: '～を(こっそり)盗む；盗みをする'},
        {en: 'sink', ja: '(水面下に)沈む；～を沈める'},
        {en: 'request', ja: '～を要請する'},
        {en: 'convince', ja: '～に納得させる'},
        {en: 'surround', ja: '<be surroundedで>囲まれている'},
        {en: 'calculate', ja: '(費用など)を計算する'},
        {en: 'criticize', ja: '～を批判する'},
        {en: 'explore', ja: '～を探検する'},
        {en: 'philosophy', ja: '哲学'},
        {en: 'personality', ja: '個性'},
        {en: 'foreigner', ja: '外国人'},
        {en: 'institution', ja: '(社会的・教育的な)機関'},
        {en: 'laboratory', ja: '実験室'},
        {en: 'option', ja: '選択(肢)'},
        {en: 'soldier', ja: '兵隊'},
        {en: 'tax', ja: '税金'},
        {en: 'fiction', ja: '(架空の)小説'},
        {en: 'capital', ja: '首都'},
        {en: 'fully', ja: '十分に'},
        {en: 'greatly', ja: '大いに'},
        {en: 'naturally', ja: '<文頭で>当然(ながら)'},
        {en: 'nevertheless', ja: 'それにもかかわらず'},
        {en: 'overseas', ja: '海外で[へ]'},
        {en: 'surely', ja: '確かに'},
        {en: 'rarely', ja: 'めったに～しない'},
        {en: 'mostly', ja: 'たいてい'},
        {en: 'moreover', ja: 'そのうえ'},
        {en: 'furthermore', ja: 'そのうえ'},
        {en: 'minister', ja: '<Ministerで>(英国・日本などの)大臣'},
        {en: 'tale', ja: '話'},
        {en: 'battle', ja: '戦闘'},
        {en: 'facility', ja: '設備'},
        {en: 'broadcast', ja: '(テレビ・ラジオの)放送'},
        {en: 'rank', ja: '地位'},
        {en: 'crisis', ja: '(政治・経済上の)危機'},
        {en: 'stuff', ja: '(漠然と)もの'},
        {en: 'reward', ja: '報酬'},
        {en: 'occupation', ja: '職業'},
        {en: 'property', ja: '財産'},
        {en: 'fee', ja: '(参加・入場などの)料金'},
        {en: 'cash', ja: '現金'},
        {en: 'agreement', ja: '協定'},
        {en: 'civilization', ja: '文明'},
        {en: 'version', ja: '(製品などの)型'},
        {en: 'leisure', ja: '余暇'},
        {en: 'enemy', ja: '敵'},
        {en: 'feather', ja: '羽'},
        {en: 'welfare', ja: '福祉'},
        {en: 'deny', ja: '～を否定する'},
        {en: 'annoy', ja: '～をいらいらさせる'},
        {en: 'differ', ja: '異なる'},
        {en: 'repeat', ja: '(発言など)を繰り返す'},
        {en: 'expose', ja: '(危険・風雨などに)～をさらす'},
        {en: 'estimate', ja: '～を[と]見積もる'},
        {en: 'transfer', ja: '(人・物など)を移動させる；移動する'},
        {en: 'recover', ja: '回復する'},
        {en: 'insult', ja: '～を侮辱する'},
        {en: 'blame', ja: '～を非難する'},
        {en: 'illustrate', ja: '～を説明する'},
        {en: 'disagree', ja: '反対する'},
        {en: 'entertain', ja: '～を楽しませる'},
        {en: 'translate', ja: '～を翻訳する'},
        {en: 'puzzle', ja: '～を困らせる'},
        {en: 'confirm', ja: '(証拠によって)～を確かめる'},
        {en: 'specialize', ja: '<specialize in Aで>Aを専門にする'},
        {en: 'dislike', ja: '～を嫌う'},
        {en: 'lift', ja: '～を持ち上げる；上がる'},
        {en: 'resist', ja: '～に抵抗する'},
        {en: 'formal', ja: '正式の'},
        {en: 'worldwide', ja: '世界的な'},
        {en: 'pleased', ja: '<be pleasedで>うれしい'},
        {en: 'nearby', ja: '近くの'},
        {en: 'remarkable', ja: '注目すべき'},
        {en: 'historical', ja: '歴史の'},
        {en: 'actual', ja: '実際の'},
        {en: 'sensitive', ja: '敏感な'},
        {en: 'firm', ja: '堅い'},
        {en: 'aggressive', ja: '攻撃的な'},
        {en: 'agriculture', ja: '農業'},
        {en: 'trick', ja: '(人をだます)策略'},
        {en: 'scene', ja: '(映画などの)シーン'},
        {en: 'capacity', ja: '容量'},
        {en: 'trap', ja: '(鳥獣用の)わな'},
        {en: 'tail', ja: '尾'},
        {en: 'army', ja: '軍隊'},
        {en: 'foundation', ja: '(物・事の)基礎'},
        {en: 'guy', ja: '(くだけて)やつ'},
        {en: 'literature', ja: '文学(作品)'},
        {en: 'election', ja: '選挙'},
        {en: 'injury', ja: 'けが'},
        {en: 'ceremony', ja: '式(典)'},
        {en: 'era', ja: '時代'},
        {en: 'furniture', ja: '家具'},
        {en: 'dozen', ja: 'ダース'},
        {en: 'architecture', ja: '建築'},
        {en: 'alcohol', ja: 'アルコール飲料'},
        {en: 'mystery', ja: 'なぞ'},
        {en: 'branch', ja: '枝'},
        {en: 'interrupt', ja: '～を中断させる'},
        {en: 'imply', ja: '～を暗示する'},
        {en: 'warn', ja: '～に警告する'},
        {en: 'persuade', ja: '～を説得する'},
        {en: 'adjust', ja: '(機器など)を調整する'},
        {en: 'advise', ja: '～に忠告する'},
        {en: 'overcome', ja: '(困難など)を克服する'},
        {en: 'permit', ja: '(～に)…を許可する'},
        {en: 'shake', ja: '～を振る'},
        {en: 'deliver', ja: '～を配達する'},
        {en: 'cure', ja: '(病気・人)を治す'},
        {en: 'select', ja: '～を(慎重に)選ぶ'},
        {en: 'investigate', ja: '～を調査する'},
        {en: 'chat', ja: '雑談する'},
        {en: 'remark', ja: '～と述べる'},
        {en: 'suspect', ja: '～であろうと思う'},
        {en: 'praise', ja: '～を賞賛する'},
        {en: 'bark', ja: 'ほえる'},
        {en: 'alter', ja: '～を変える'},
        {en: 'commit', ja: '(犯罪など)を犯す'},
        {en: 'narrow', ja: '(幅の)狭い'},
        {en: 'nuclear', ja: '原子力の'},
        {en: 'strict', ja: '厳しい'},
        {en: 'alive', ja: '生きて'},
        {en: 'severe', ja: '深刻な'},
        {en: 'satisfied', ja: '<be satisfiedで>満足している'},
        {en: 'intellectual', ja: '知的な'},
        {en: 'civil', ja: '市民(として)の'},
        {en: 'unexpected', ja: '思いがけない'},
        {en: 'junior', ja: '後輩の'},
        {en: 'label', ja: 'ラベル'},
        {en: 'snack', ja: '(食間の)軽食'},
        {en: 'shame', ja: '恥ずかしさ'},
        {en: 'automobile', ja: '自動車 《主に米》'},
        {en: 'flood', ja: '洪水'},
        {en: 'oxygen', ja: '酸素'},
        {en: 'layer', ja: '層'},
        {en: 'perspective', ja: '視点'},
        {en: 'depression', ja: '不景気'},
        {en: 'adventure', ja: '冒険'},
        {en: 'category', ja: '範ちゅう'},
        {en: 'tragedy', ja: '悲劇(的事件)'},
        {en: 'diversity', ja: '多様性'},
        {en: 'notion', ja: '(漠然とした)考え'},
        {en: 'tribe', ja: '部族'},
        {en: 'sector', ja: '(産業・経済などの)部門'},
        {en: 'joy', ja: '喜び'},
        {en: 'instruction', ja: '<instructionsで>指示'},
        {en: 'trial', ja: '裁判'},
        {en: 'theme', ja: '主題'},
        {en: 'lend', ja: '(…に)～を貸す'},
        {en: 'analyze', ja: '～を分析する'},
        {en: 'present', ja: '～を[に]贈呈する'},
        {en: 'fold', ja: '～を折りたたむ'},
        {en: 'emphasize', ja: '～を強調する'},
        {en: 'rent', ja: '～を(有料で)借りる'},
        {en: 'construct', ja: '～を建設する'},
        {en: 'protest', ja: '(～に)抗議する'},
        {en: 'owe', ja: '(…に)～の借金がある'},
        {en: 'absorb', ja: '(養分・知識など)を吸収する'},
        {en: 'elderly', ja: '年配の'},
        {en: 'plain', ja: '明らかな'},
        {en: 'rural', ja: '田舎の'},
        {en: 'reasonable', ja: '分別のある'},
        {en: 'stable', ja: '(状態が)安定した'},
        {en: 'helpful', ja: '役に立つ'},
        {en: 'visual', ja: '視覚の'},
        {en: 'surprising', ja: '驚くべき'},
        {en: 'initial', ja: '最初の'},
        {en: 'solar', ja: '太陽の'},
        {en: 'lung', ja: '肺'},
        {en: 'resident', ja: '居住者'},
        {en: 'quarter', ja: '4分の1'},
        {en: 'agent', ja: '代理人'},
        {en: 'chart', ja: '図'},
        {en: 'gravity', ja: '重力'},
        {en: 'investment', ja: '(企業・銀行などへの)投資'},
        {en: 'length', ja: '(物・時間などの)長さ'},
        {en: 'arrival', ja: '到着'},
        {en: 'institute', ja: '(学術・教育などの)学会'},
        {en: 'partner', ja: '仲間'},
        {en: 'alarm', ja: '驚き'},
        {en: 'executive', ja: '(組織の)幹部'},
        {en: 'tip', ja: '(とがったものの)先'},
        {en: 'shortage', ja: '不足'},
        {en: 'lawyer', ja: '弁護士'},
        {en: 'victim', ja: '犠牲者'},
        {en: 'innovation', ja: '革新'},
        {en: 'bay', ja: '(小さい)湾'},
        {en: 'volcano', ja: '火山'},
        {en: 'abandon', ja: '(国・家族・乗り物など)を捨てる'},
        {en: 'forecast', ja: '(情報に基づいて)～を予想[予測]する'},
        {en: 'disturb', ja: '～をじゃまする'},
        {en: 'declare', ja: '～を宣言する'},
        {en: 'pause', ja: 'ちょっと止まる'},
        {en: 'capture', ja: '～を捕える'},
        {en: 'attach', ja: '<attach A to Bで>AをBに付ける'},
        {en: 'pack', ja: '(かばんなど)に荷物を詰める'},
        {en: 'guarantee', ja: '～を保証する'},
        {en: 'imitate', ja: '～をまねる'},
        {en: 'smart', ja: '頭のよい 《主に米》'},
        {en: 'deaf', ja: '耳が聞こえない'},
        {en: 'capable', ja: '<be capable of Aで>Aの[Aする]能力がある'},
        {en: 'evil', ja: '悪い'},
        {en: 'flat', ja: '(表面が)平らな'},
        {en: 'chief', ja: '(階級・権限が)最高位の'},
        {en: 'artificial', ja: '人工の'},
        {en: 'inner', ja: '内側の'},
        {en: 'mere', ja: '単なる'},
        {en: 'contemporary', ja: '現代の'},
        {en: 'fossil', ja: '化石'},
        {en: 'fault', ja: '<one’s faultで>責任'},
        {en: 'reputation', ja: '評判'},
        {en: 'regulation', ja: '<regulationsで>規則'},
        {en: 'debt', ja: '借金'},
        {en: 'route', ja: '経路'},
        {en: 'disorder', ja: '(心身の)不調'},
        {en: 'honor', ja: '名誉'},
        {en: 'ease', ja: '容易さ'},
        {en: 'substance', ja: '物質'},
        {en: 'dye', ja: '～を染める'},
        {en: 'breed', ja: '(動物が)繁殖する；(動植物)を繁殖させる'},
        {en: 'inspire', ja: '～を奮起させる'},
        {en: 'hesitate', ja: 'ためらう'},
        {en: 'collapse', ja: '(建物などが)崩壊する'},
        {en: 'stretch', ja: '～を伸ばす；伸びる'},
        {en: 'pretend', ja: '～のふりをする'},
        {en: 'melt', ja: '溶ける；～を溶かす'},
        {en: 'pose', ja: '(危険・問題など)をもたらす'},
        {en: 'operate', ja: '(機械など)を操作する；(機械などが)動く'},
        {en: 'senior', ja: '年上の'},
        {en: 'related', ja: '関係のある'},
        {en: 'dramatic', ja: '劇的な'},
        {en: 'lonely', ja: 'さびしい'},
        {en: 'electronic', ja: '電子(式)の'},
        {en: 'contrary', ja: '反対の'},
        {en: 'scared', ja: '<be scaredで>怖がる'},
        {en: 'anxious', ja: '心配して'},
        {en: 'manual', ja: '手動の'},
        {en: 'giant', ja: '巨大な'},
        {en: 'folk', ja: '<folksで>人々'},
        {en: 'client', ja: '(弁護士などへの)依頼人'},
        {en: 'peak', ja: '(活動・過程などの)絶頂'},
        {en: 'mood', ja: '気分'},
        {en: 'iron', ja: '鉄'},
        {en: 'pole', ja: '(地球・天体の)極'},
        {en: 'entry', ja: '入ること'},
        {en: 'contract', ja: '契約(書)'},
        {en: 'volume', ja: '量'},
        {en: 'lifetime', ja: '一生'},
        {en: 'beat', ja: '(～を)たたく'},
        {en: 'stimulate', ja: '～を刺激する'},
        {en: 'dive', ja: '(水中に)飛び込む'},
        {en: 'ensure', ja: '～を確実にする'},
        {en: 'detect', ja: '～を見つける'},
        {en: 'cancel', ja: '～を取り消す'},
        {en: 'explode', ja: '爆発する'},
        {en: 'export', ja: '～を輸出する'},
        {en: 'accomplish', ja: '～を達成する'},
        {en: 'acknowledge', ja: ' (事実・過失など)を認める'},
        {en: 'marine', ja: '海の'},
        {en: 'curious', ja: '好奇心の強い'},
        {en: 'pure', ja: '純粋な'},
        {en: 'extraordinary', ja: '並はずれた'},
        {en: 'upper', ja: '(2つのうち)上の(方の)'},
        {en: 'precise', ja: '正確な'},
        {en: 'amazing', ja: 'びっくりするような'},
        {en: 'proper', ja: '適切な'},
        {en: 'sufficient', ja: '十分な'},
        {en: 'brief', ja: '短時間の'},
        {en: 'truly', ja: '本当に'},
        {en: 'unfortunately', ja: '残念ながら'},
        {en: 'necessarily', ja: '<not necessarilyで>必ずしも～ない'},
        {en: 'regardless', ja: '<regardless of Aで>Aに関係なく'},
        {en: 'apart', ja: '(距離が)離れて'},
        {en: 'apparently', ja: '(見た[聞いた]ところ)どうも～らしい'},
        {en: 'badly', ja: 'まずく'},
        {en: 'somewhat', ja: 'やや'},
        {en: 'definitely', ja: '確かに'},
        {en: 'largely', ja: '主に'},
        {en: 'everywhere', ja: 'あらゆる所で[へ]'},
        {en: 'deeply', ja: '非常に'},
        {en: 'fairly', ja: 'かなり'},
        {en: 'absolutely', ja: '完全に'},
        {en: 'aside', ja: '脇に'},
        {en: 'somehow', ja: '(理由は不明だが)どういうわけか'},
        {en: 'partly', ja: '部分的に(は)'},
        {en: 'afterward(s)', ja: 'あとで'},
        {en: 'nowadays', ja: '近ごろ(は)'},
        {en: 'virtually', ja: '(厳密には違うが)実質的に(は)'},
        {en: 'laughter', ja: '笑い'},
        {en: 'shelter', ja: '避難'},
        {en: 'procedure', ja: '手順'},
        {en: 'appointment', ja: '(面会の)約束'},
        {en: 'tone', ja: '口調'},
        {en: 'border', ja: '国境'},
        {en: 'height', ja: '高さ'},
        {en: 'outcome', ja: '(最終的な)結果'},
        {en: 'motion', ja: '運動'},
        {en: 'exit', ja: '出口'},
        {en: 'corporation', ja: '企業'},
        {en: 'conservation', ja: '(天然資源・文化財などの)保護'},
        {en: 'symptom', ja: '(患者の)症状'},
        {en: 'string', ja: 'ひも'},
        {en: 'mission', ja: '(外国などへの)使節(団)'},
        {en: 'fellow', ja: '男'},
        {en: 'sample', ja: '見本'},
        {en: 'campus', ja: '(大学などの)キャンパス'},
        {en: 'wisdom', ja: '知恵'},
        {en: 'statue', ja: '像'},
        {en: 'interpret', ja: '～を解釈する'},
        {en: 'oppose', ja: '～に反対する'},
        {en: 'defend', ja: '(～を)守る'},
        {en: 'eliminate', ja: '～を排除する'},
        {en: 'compose', ja: '～を構成する'},
        {en: 'generate', ja: '～を生み出す'},
        {en: 'command', ja: '～を[に]命令する'},
        {en: 'pour', ja: '～を注ぐ'},
        {en: 'ruin', ja: '～を破滅させる'},
        {en: 'hire', ja: '～を雇う 《主に米》'},
        {en: 'steady', ja: '安定した'},
        {en: 'considerable', ja: '(量・数・程度などが)かなりの'},
        {en: 'polite', ja: '礼儀正しい'},
        {en: 'secure', ja: '安全な'},
        {en: 'blind', ja: '目の見えない'},
        {en: 'remote', ja: '(距離的)遠く離れた'},
        {en: 'dirty', ja: '汚れた'},
        {en: 'apparent', ja: '明白な'},
        {en: 'pleasant', ja: '楽しい'},
        {en: 'stupid', ja: 'ばかげた'},
        {en: 'continent', ja: '大陸'},
        {en: 'vision', ja: '視力'},
        {en: 'register', ja: '登録(簿)'},
        {en: 'crew', ja: '(集合的に)乗組員'},
        {en: 'shore', ja: '(海・湖・川などの)岸'},
        {en: 'fate', ja: '運命'},
        {en: 'biology', ja: '生物学'},
        {en: 'stock', ja: '(物の)蓄え'},
        {en: 'hunger', ja: '飢え'},
        {en: 'objective', ja: '(達成すべき)目標'},
        {en: 'sweat', ja: '汗'},
        {en: 'infant', ja: '(乳)幼児'},
        {en: 'minority', ja: '(ある集団の)少数'},
        {en: 'wheel', ja: '車輪'},
        {en: 'affair', ja: '<affairsで>事務'},
        {en: 'landscape', ja: '(一望できる陸地の)風景'},
        {en: 'loan', ja: 'ローン'},
        {en: 'incident', ja: '(小さな)出来事'},
        {en: 'routine', ja: 'いつもすること'},
        {en: 'humanity', ja: '人間性'},
        {en: 'transform', ja: '～を変化させる'},
        {en: 'glance', ja: '(意図的に)ちらりと見る'},
        {en: 'quit', ja: '(仕事・学校など)をやめる；辞職する'},
        {en: 'mix', ja: '～を混ぜる；混ざる'},
        {en: 'combine', ja: '～を組み合わせる'},
        {en: 'extend', ja: '～を拡大する；広がる'},
        {en: 'accompany', ja: '～に同行する'},
        {en: 'dig', ja: '(～を)掘る'},
        {en: 'cope', ja: '<cope with Aで>Aをうまく処理する'},
        {en: 'apologize', ja: '謝罪する'},
        {en: 'visible', ja: '(目に)見える'},
        {en: 'crucial', ja: '決定的な'},
        {en: 'numerous', ja: '多数の'},
        {en: 'sudden', ja: '突然の'},
        {en: 'superior', ja: '(他者より)優れた'},
        {en: 'grand', ja: '(建物・景色・計画などが)壮大な'},
        {en: 'eager', ja: '<be eagerで>熱望している'},
        {en: 'latter', ja: '<the latterで>(2つのうちの)後者の'},
        {en: 'solid', ja: '固体の'},
        {en: 'collective', ja: '集団による'},
        {en: 'imagination', ja: '想像力'},
        {en: 'treasure', ja: '財宝'},
        {en: 'obstacle', ja: '(目標達成をはばむ)障害'},
        {en: 'harmony', ja: '(感情・意見などの)一致'},
        {en: 'myth', ja: '神話'},
        {en: 'transition', ja: '移り変わり'},
        {en: 'barrier', ja: '防壁'},
        {en: 'seed', ja: '種'},
        {en: 'headache', ja: '頭痛'},
        {en: 'sum', ja: '<the sumで>合計'},
        {en: 'opponent', ja: '(試合・討論などの)相手'},
        {en: 'component', ja: '(構成)要素'},
        {en: 'duty', ja: '義務'},
        {en: 'priority', ja: '優先事項'},
        {en: 'psychology', ja: '心理学'},
        {en: 'wage', ja: '賃金'},
        {en: 'core', ja: '<the coreで>中心(部分)'},
        {en: 'mineral', ja: '鉱物'},
        {en: 'shadow', ja: '(人や物の)影'},
        {en: 'genius', ja: '天才'},
        {en: 'exhibit', ja: '～を展示する'},
        {en: 'distinguish', ja: '(～を)見分ける'},
        {en: 'yield', ja: '(作物など)を産出する'},
        {en: 'fix', ja: '～を固定する'},
        {en: 'possess', ja: '～を所有している'},
        {en: 'inform', ja: '～に通知する'},
        {en: 'evaluate', ja: '～を評価する'},
        {en: 'urge', ja: '～を促す'},
        {en: 'deserve', ja: '～に値する'},
        {en: 'sue', ja: '(～を)告訴する'},
        {en: 'rude', ja: '失礼な'},
        {en: 'absent', ja: '欠席して'},
        {en: 'frightened', ja: 'おびえた'},
        {en: 'internal', ja: '内部の'},
        {en: 'minor', ja: '小さな'},
        {en: 'awake', ja: '目が覚めて'},
        {en: 'exhausted', ja: '疲れ果てた'},
        {en: 'mad', ja: '頭にきて'},
        {en: 'tropical', ja: '熱帯(地方)の'},
        {en: 'prime', ja: '最重要な'},
        {en: 'committee', ja: '委員会'},
        {en: 'sequence', ja: '<a［the］ sequence of Aで>一連のA'},
        {en: 'legend', ja: '伝説'},
        {en: 'review', ja: '再調査'},
        {en: 'justice', ja: '正義'},
        {en: 'crash', ja: '(車などの)衝突'},
        {en: 'ray', ja: '<raysで>光線'},
        {en: 'budget', ja: '予算'},
        {en: 'tension', ja: '(精神的)緊張'},
        {en: 'sake', ja: '<for one’s sakeで>～の(利益・目的の)ために'},
        {en: 'harvest', ja: '(作物の)収穫'},
        {en: 'salary', ja: '給料'},
        {en: 'nest', ja: '巣'},
        {en: 'zone', ja: '(用途・特徴で区分される)地帯'},
        {en: 'insurance', ja: '保険'},
        {en: 'dispute', ja: '論争'},
        {en: 'summit', ja: '<the summitで>頂上'},
        {en: 'wound', ja: '傷'},
        {en: 'candidate', ja: '(立)候補者'},
        {en: 'load', ja: '(大量の重い)積み荷'},
        {en: 'wrap', ja: '～を包む'},
        {en: 'confront', ja: '<be confrontedで>(困難などに)直面する'},
        {en: 'dominate', ja: '～を支配する'},
        {en: 'arrest', ja: '～を逮捕する'},
        {en: 'reverse', ja: '～を逆にする'},
        {en: 'nod', ja: 'うなずく'},
        {en: 'weaken', ja: '～を弱める'},
        {en: 'float', ja: '浮かぶ；～を浮かべる'},
        {en: 'sustain', ja: '(活動・状態など)を持続させる'},
        {en: 'sail', ja: '(～を)航海する'},
        {en: 'consistent', ja: '(言動・考えなどが)(首尾)一貫した'},
        {en: 'raw', ja: '生の'},
        {en: 'classic', ja: '典型的な'},
        {en: 'instant', ja: '即座の'},
        {en: 'crazy', ja: '正気でない'},
        {en: 'reluctant', ja: '<be reluctant to doで>～したがらない'},
        {en: 'peaceful', ja: '平和な'},
        {en: 'outdoor', ja: '野外の'},
        {en: 'ethical', ja: '道徳上の'},
        {en: 'precious', ja: '(物・時間などが)貴重な'},
        {en: 'cattle', ja: '畜牛'},
        {en: 'luxury', ja: 'ぜいたく'},
        {en: 'valley', ja: '(川の流れる)谷'},
        {en: 'fund', ja: '基金'},
        {en: 'cough', ja: 'せき(払い)'},
        {en: 'virus', ja: 'ウイルス'},
        {en: 'tongue', ja: '舌'},
        {en: 'prejudice', ja: '偏見'},
        {en: 'emergency', ja: '緊急(事態)'},
        {en: 'delight', ja: '大喜び'},
        {en: 'discourage', ja: '～を落胆させる'},
        {en: 'scream', ja: '悲鳴をあげる'},
        {en: 'resolve', ja: '～を解決する'},
        {en: 'trace', ja: '(出所など)を明らかにする'},
        {en: 'fulfill', ja: '(義務・約束など)を果たす'},
        {en: 'hunt', ja: '～を狩る；狩りをする'},
        {en: 'heal', ja: '(傷などが)治る'},
        {en: 'rid', ja: '<rid A of Bで>AからBを取り除く'},
        {en: 'inherit', ja: '～を相続する'},
        {en: 'attribute', ja: '<attribute A to Bで>AをBのせいにする'},
        {en: 'mild', ja: '(気候が)温暖な'},
        {en: 'extinct', ja: '絶滅した'},
        {en: 'underground', ja: '地下の'},
        {en: 'smooth', ja: '(表面が)なめらかな'},
        {en: 'wise', ja: '賢明な'},
        {en: 'rough', ja: '(表面が)でこぼこの'},
        {en: 'ethnic', ja: '民族の'},
        {en: 'permanent', ja: '永久的な'},
        {en: 'neat', ja: 'きちんとした'},
        {en: 'wooden', ja: '木製の'},
        {en: 'restriction', ja: '制限'},
        {en: 'fever', ja: '(病気の)熱'},
        {en: 'dust', ja: 'ほこり'},
        {en: 'grain', ja: '穀物'},
        {en: 'gender', ja: '(社会的・文化的観点から見た)性(差)'},
        {en: 'award', ja: '賞'},
        {en: 'humor', ja: 'ユーモア'},
        {en: 'excitement', ja: '興奮(状態)'},
        {en: 'enthusiasm', ja: '熱意'},
        {en: 'convention', ja: '(定期的な)大会'},
        {en: 'pursue', ja: '(目的など)を追求する'},
        {en: 'retain', ja: '～を保持する'},
        {en: 'pronounce', ja: '～を発音する'},
        {en: 'endure', ja: '(困難・苦痛など)に耐える'},
        {en: 'punish', ja: '～を罰する'},
        {en: 'scratch', ja: '～を(爪などで)かく'},
        {en: 'wander', ja: '(目的もなく)歩き回る'},
        {en: 'shoot', ja: '(銃で)(～を)撃つ'},
        {en: 'bury', ja: '(物)を埋める'},
        {en: 'consult', ja: '(専門家など)に相談する'},
        {en: 'bare', ja: 'むき出しの'},
        {en: 'abstract', ja: '抽象的な'},
        {en: 'mature', ja: '成熟した'},
        {en: 'alike', ja: '似ている'},
        {en: 'innocent', ja: '無罪の'},
        {en: 'modest', ja: '謙虚な'},
        {en: 'intense', ja: '(光・熱などが)強烈な'},
        {en: 'awful', ja: 'ひどい'},
        {en: 'urgent', ja: '緊急の'},
        {en: 'loose', ja: '(結び目などが)ゆるい'},
        {en: 'colony', ja: '植民地'},
        {en: 'railroad', ja: '鉄道 《米》'},
        {en: 'commitment', ja: '約束'},
        {en: 'sacrifice', ja: '犠牲'},
        {en: 'ceiling', ja: '天井'},
        {en: 'garbage', ja: 'ごみ 《主に米》'},
        {en: 'weapon', ja: '兵器'},
        {en: 'invasion', ja: '侵入'},
        {en: 'fare', ja: '(交通機関の)料金'},
        {en: 'territory', ja: '領土'},
        {en: 'bet', ja: '～を賭ける'},
        {en: 'dismiss', ja: '(提案・考えなどを)を退ける'},
        {en: 'submit', ja: '～を提出する'},
        {en: 'divorce', ja: '～と離婚する'},
        {en: 'convey', ja: '(感情・思考など)を伝える'},
        {en: 'burst', ja: '破裂する'},
        {en: 'guard', ja: '～を守る'},
        {en: 'swallow', ja: '(飲食物)を飲み込む'},
        {en: 'manufacture', ja: '～を生産する'},
        {en: 'convert', ja: '<convert A into[to] Bで>AをBに変える'},
        {en: 'vital', ja: '不可欠な'},
        {en: 'odd', ja: '奇妙な'},
        {en: 'primitive', ja: '原始的な'},
        {en: 'flexible', ja: '(考え・計画などが)柔軟な'},
        {en: 'uneasy', ja: '不安な'},
        {en: 'prompt', ja: '迅速な'},
        {en: 'distinct', ja: '別個の'},
        {en: 'pale', ja: '(顔などが)青白い'},
        {en: 'clever', ja: '頭のよい 《主に英》'},
        {en: 'fluent', ja: '(外国語などが)流ちょうな'},
        {en: 'meanwhile', ja: 'その間(に)'},
        {en: 'seldom', ja: 'めったに～しない'},
        {en: 'approximately', ja: 'おおよそ'},
        {en: 'literally', ja: '文字どおりに'},
        {en: 'barely', ja: 'かろうじて'},
        {en: 'forever', ja: '永遠に'},
        {en: 'lately', ja: '最近'},
        {en: 'altogether', ja: 'まったく'},
        {en: 'namely', ja: 'すなわち'},
        {en: 'upstairs', ja: '階上へ[で]'},
        {en: 'burden', ja: '(精神的な)重荷'},
        {en: 'discrimination', ja: '差別(待遇)'},
        {en: 'heritage', ja: '(文化的な)遺産'},
        {en: 'discipline', ja: '訓練'},
        {en: 'dawn', ja: '夜明け'},
        {en: 'steam', ja: '(水)蒸気'},
        {en: 'boundary', ja: '境界(線)'},
        {en: 'scheme', ja: '(政府・企業による)(事業)計画 《主に英》'},
        {en: 'fortune', ja: '富'},
        {en: 'abuse', ja: '(権力・薬などの)乱用'},
        {en: 'witness', ja: '目撃者'},
        {en: 'expense', ja: '費用'},
        {en: 'depth', ja: '深さ'},
        {en: 'pile', ja: '(物を積み上げた)山'},
        {en: 'reform', ja: '(制度・法律などの)改革'},
        {en: 'prospect', ja: '(成功などの)見込み'},
        {en: 'fame', ja: '名声'},
        {en: 'proof', ja: '証拠'},
        {en: 'compromise', ja: '妥協'},
        {en: 'output', ja: '生産高'},
        {en: 'associate', ja: '<associate A with Bで>AとBを結びつけて考える'},
        {en: 'neglect', ja: '～を軽視[無視]する'},
        {en: 'bend', ja: '(物が)曲がる'},
        {en: 'vanish', ja: '消える'},
        {en: 'persist', ja: '固執する'},
        {en: 'spoil', ja: '～をだめにする'},
        {en: 'sigh', ja: 'ため息をつく'},
        {en: 'cultivate', ja: '(土地)を耕す'},
        {en: 'perceive', ja: '(特に視覚によって)～に気づく'},
        {en: 'greet', ja: '～にあいさつする'},
        {en: 'assign', ja: '～を割り当てる'},
        {en: 'lean', ja: '(物が)傾く'},
        {en: 'cease', ja: '(雨・音などが)やむ'},
        {en: 'tear', ja: '～を破る'},
        {en: 'gaze', ja: '(喜び・興味を持って)見つめる'},
        {en: 'cheer', ja: '～を元気づける'},
        {en: 'advertise', ja: '～を宣伝する'},
        {en: 'boil', ja: '～を沸かす；沸騰する'},
        {en: 'defeat', ja: '(試合・戦争などで)～を破る'},
        {en: 'leap', ja: '跳ぶ'},
        {en: 'fond', ja: '<be fond of Aで>Aが大好きである'},
        {en: 'ultimate', ja: '究極の'},
        {en: 'bored', ja: '退屈して'},
        {en: 'principal', ja: '主要な'},
        {en: 'sophisticated', ja: '(人・服装などが)洗練された'},
        {en: 'concrete', ja: '具体的な'},
        {en: 'passive', ja: '受動的な'},
        {en: 'dull', ja: '退屈な'},
        {en: 'gross', ja: '総計の'},
        {en: 'foolish', ja: '愚かな'},
        {en: 'pioneer', ja: '先駆者'},
        {en: 'secretary', ja: '秘書'},
        {en: 'appetite', ja: '食欲'},
        {en: 'inhabitant', ja: '<inhabitantsで>住民'},
        {en: 'avenue', ja: '大通り'},
        {en: 'clue', ja: '(解決への)手がかり'},
        {en: 'wheat', ja: '小麦'},
        {en: 'victory', ja: '(試合・選挙などの)勝利'},
        {en: 'estate', ja: '財産'},
        {en: 'bond', ja: 'きずな'},
        {en: 'instinct', ja: '本能'},
        {en: 'poll', ja: '<the poll(s)で>投票'},
        {en: 'resort', ja: '保養地'},
        {en: 'companion', ja: '(共に行動する)仲間'},
        {en: 'mess', ja: '散らかった状態'},
        {en: 'baggage', ja: '(旅行用の)手荷物 《主に米》'},
        {en: 'prison', ja: '刑務所'},
        {en: 'mechanism', ja: '仕組み'},
        {en: 'courage', ja: '勇気'},
        {en: 'sympathy', ja: '同情'},
        {en: 'resemble', ja: '～に似ている'},
        {en: 'constitute', ja: '(物・集団など)を構成する'},
        {en: 'obey', ja: '(命令・人・規則など)に従う'},
        {en: 'interfere', ja: '<interfere in Aで>Aに干渉する'},
        {en: 'distribute', ja: '～を分配する'},
        {en: 'cooperate', ja: '協力する'},
        {en: 'fascinate', ja: '～を魅了する'},
        {en: 'substitute', ja: '<substitute A for Bで>AをBの代わりに使う'},
        {en: 'quote', ja: '(文・語句など)を引用する'},
        {en: 'freeze', ja: '凍る；～を凍らせる'},
        {en: 'overlook', ja: '(建物・窓などが)～を見下ろす'},
        {en: 'whisper', ja: '(～を)ささやく'},
        {en: 'modify', ja: '(意見・計画など)を変更する'},
        {en: 'slide', ja: 'すべる；～をすべらせる'},
        {en: 'offend', ja: '～の気分を害する'},
        {en: 'impose', ja: '<impose A on Bで>A[義務・制限・罰金など]をBに課す'},
        {en: 'edit', ja: '～を編集する'},
        {en: 'prohibit', ja: '<prohibit A from doingで>Aが～するのを禁止する'},
        {en: 'withdraw', ja: '(活動・組織から)退く；～を退かせる'},
        {en: 'anticipate', ja: '～を予想する'},
        {en: 'relevant', ja: '(密接に)関連した'},
        {en: 'guilty', ja: '罪を犯した'},
        {en: 'vivid', ja: '(記憶・描写などが)鮮明な'},
        {en: 'acid', ja: '酸性の'},
        {en: 'moderate', ja: '(人・考えなどが)穏健な'},
        {en: 'racial', ja: '人種的な'},
        {en: 'awkward', ja: '(状況などが)気まずい'},
        {en: 'prominent', ja: '卓越した'},
        {en: 'generous', ja: '気前のよい'},
        {en: 'ashamed', ja: '<be ashamedで>恥じている'},
        {en: 'soul', ja: '魂'},
        {en: 'vessel', ja: '(大型の)船'},
        {en: 'quarrel', ja: '口論'},
        {en: 'crack', ja: '割れ目'},
        {en: 'session', ja: '会合'},
        {en: 'portion', ja: '部分'},
        {en: 'pity', ja: '残念なこと'},
        {en: 'faith', ja: '(信念に基づく)信頼'},
        {en: 'tune', ja: '曲'},
        {en: 'angle', ja: '角度'},
        {en: 'council', ja: '評議会'},
        {en: 'anniversary', ja: '(毎年の)記念日'},
        {en: 'strain', ja: '(精神的)緊張'},
        {en: 'miracle', ja: '奇跡'},
        {en: 'ambition', ja: '熱望'},
        {en: 'parliament', ja: '(英国などの)議会'},
        {en: 'column', ja: '(建物の)柱'},
        {en: 'faculty', ja: '(大学の)学部'},
        {en: 'flag', ja: '旗'},
        {en: 'fog', ja: '霧'},
        {en: 'assist', ja: '～を(補助的に)助ける'},
        {en: 'forbid', ja: '(…に)～を禁じる'},
        {en: 'propose', ja: '～を提案する'},
        {en: 'rescue', ja: '～を救出する'},
        {en: 'chase', ja: '～を追いかける'},
        {en: 'devote', ja: '(時間・金・努力など)をささげる'},
        {en: 'assure', ja: '～に保証する'},
        {en: 'rub', ja: '～をこする'},
        {en: 'fade', ja: '(人・物が)見えなくなる'},
        {en: 'polish', ja: '～を磨く'},
        {en: 'silly', ja: '愚かな'},
        {en: 'tight', ja: 'きつい'},
        {en: 'elegant', ja: '上品な'},
        {en: 'gentle', ja: '優しい'},
        {en: 'adequate', ja: '十分な'},
        {en: 'continuous', ja: '絶え間ない'},
        {en: 'brave', ja: '勇敢な'},
        {en: 'jealous', ja: 'ねたんで'},
        {en: 'incredible', ja: '信じられない'},
        {en: 'lazy', ja: '怠け者の'},
        {en: 'unity', ja: '統一'},
        {en: 'murder', ja: '殺人'},
        {en: 'fantasy', ja: '空想'},
        {en: 'harbor', ja: '(自然の地形を活かした)港'},
        {en: 'funeral', ja: '葬式'},
        {en: 'organ', ja: '(動植物の)器官'},
        {en: 'geography', ja: '<the geographyで>(ある場所の)地理'},
        {en: 'passion', ja: '情熱'},
        {en: 'sorrow', ja: '(深い)悲しみ'},
        {en: 'excess', ja: '超過'},
        {en: 'frustrate', ja: '～を(欲求)不満にさせる'},
        {en: 'spill', ja: '～をこぼす；こぼれる'},
        {en: 'exceed', ja: '～を超える'},
        {en: 'restore', ja: '～を回復させる'},
        {en: 'squeeze', ja: '～を絞る'},
        {en: 'stir', ja: '(液体など)をかき混ぜる'},
        {en: 'wipe', ja: '(物の表面)をふく'},
        {en: 'infect', ja: '(病気を)～に感染させる'},
        {en: 'bathe', ja: '入浴する；～を入浴させる'},
        {en: 'shrink', ja: '縮む；～を縮ませる'},
        {en: 'sensible', ja: '賢明な'},
        {en: 'frank', ja: '率直な'},
        {en: 'maximum', ja: '最大の'},
        {en: 'miserable', ja: 'みじめな'},
        {en: 'mutual', ja: '相互の'},
        {en: 'useless', ja: '役に立たない'},
        {en: 'genuine', ja: '本物の'},
        {en: 'grateful', ja: '<be gratefulで>感謝する'},
        {en: 'spare', ja: '余分の'},
        {en: 'tremendous', ja: 'ものすごい'},
        {en: 'district', ja: '(特定の機能・特徴を持つ)地域'},
        {en: 'voyage', ja: '(長い)船旅'},
        {en: 'affection', ja: '(持続的で深い)愛情'},
        {en: 'virtue', ja: '(美)徳'},
        {en: 'phase', ja: '(変化・発展の)段階'},
        {en: 'blossom', ja: '(果樹などの)花'},
        {en: 'merit', ja: '長所'},
        {en: 'slave', ja: '奴隷'},
        {en: 'horror', ja: '(嫌悪感を伴う)恐怖'},
        {en: 'illusion', ja: '幻想'},
        {en: 'approve', ja: '(行動・計画などに)賛成する'},
        {en: 'assemble', ja: '集まる；～を集める'},
        {en: 'decorate', ja: '～を飾る'},
        {en: 'dare', ja: '<dare (to) do で>あえて～する'},
        {en: 'prevail', ja: '普及している'},
        {en: 'grasp', ja: '～を握る'},
        {en: 'seize', ja: '～を(ぐいと)つかむ'},
        {en: 'misunderstand', ja: '～を誤解する'},
        {en: 'confess', ja: '～を告白する'},
        {en: 'conquer', ja: '～を征服する'},
        {en: 'sore', ja: '痛い'},
        {en: 'bitter', ja: 'つらい'},
        {en: 'peculiar', ja: '特有の'},
        {en: 'inevitable', ja: '避けられない'},
        {en: 'conservative', ja: '(人・考え方などが)保守的な'},
        {en: 'cruel', ja: '残酷な'},
        {en: 'careless', ja: '不注意な'},
        {en: 'faint', ja: '(音・光・色などが)かすかな'},
        {en: 'overwhelming', ja: '圧倒的な'},
        {en: 'selfish', ja: 'わがままな'},
        {en: 'republic', ja: '共和国'},
        {en: 'enterprise', ja: '企業'},
        {en: 'despair', ja: '絶望'},
        {en: 'privilege', ja: '(官職・地位などに伴う)特権'},
        {en: 'liberty', ja: '(束縛からの)自由'},
        {en: 'machinery', ja: '(集合的に)機械(類)'},
        {en: 'dignity', ja: '威厳'},
        {en: 'motive', ja: '(行動などの)動機'},
        {en: 'rumor', ja: 'うわさ'},
        {en: 'impulse', ja: '衝動'},
        {en: 'cheat', ja: '～をだます'},
        {en: 'postpone', ja: '～を延期する'},
        {en: 'monitor', ja: '(状況など)を監視する'},
        {en: 'proceed', ja: '<proceed with Aで>Aを続ける'},
        {en: 'retire', ja: '(定年で)退職する'},
        {en: 'negotiate', ja: '交渉する'},
        {en: 'oblige', ja: '～を義務づける'},
        {en: 'boast', ja: '自慢する'},
        {en: 'pray', ja: '祈る'},
        {en: 'starve', ja: '餓える'},
        {en: 'random', ja: '無作為の'},
        {en: 'radical', ja: '根本的な'},
        {en: 'alert', ja: '油断のない'},
        {en: 'outstanding', ja: '目立った'},
        {en: 'ugly', ja: '(外見が)醜い'},
        {en: 'temporary', ja: '一時的な'},
        {en: 'fierce', ja: '(行為・気性・風雨などが)激しい'},
        {en: 'vague', ja: '(言葉・考え・態度などが)あいまいな'},
        {en: 'sacred', ja: '神聖な'},
        {en: 'imaginary', ja: '想像上の'},
        {en: 'suburb', ja: '<the suburbsで>(大都市の)郊外'},
        {en: 'acquaintance', ja: '知り合い'},
        {en: 'charm', ja: '魅力'},
        {en: 'departure', ja: '出発'},
        {en: 'congress', ja: '<Congressで>(米国・中南米諸国の)議会'},
        {en: 'constitution', ja: '憲法'},
        {en: 'suicide', ja: '自殺'},
        {en: 'caution', ja: '用心'},
        {en: 'treaty', ja: '条約'},
        {en: 'pension', ja: '年金'},
        {en: 'multiply', ja: '～を(大幅に)増やす'},
        {en: 'descend', ja: '(場所から)降りる'},
        {en: 'rob', ja: '<rob A of Bで>AからBを奪う'},
        {en: 'unite', ja: '～を結合させる；結合する'},
        {en: 'beg', ja: '～を[に]懇願する'},
        {en: 'omit', ja: '～を除外する'},
        {en: 'suspend', ja: '(一時的に)～を停止する'},
        {en: 'conceal', ja: '(人・物など)を隠す'},
        {en: 'forgive', ja: '～を許す'},
        {en: 'correspond', ja: '<correspond with[to] Aで>Aに一致する'},
        {en: 'sincere', ja: '誠実な'},
        {en: 'bold', ja: '大胆な'},
        {en: 'parallel', ja: '(線・面などが)平行の'},
        {en: 'thorough', ja: '徹底的な'},
        {en: 'supreme', ja: '(地位・権力・程度・質などが)最高の'},
        {en: 'splendid', ja: 'すばらしい'},
        {en: 'apt', ja: '<be apt to doで>～しがちである'},
        {en: 'brilliant', ja: 'すばらしい'},
        {en: 'elaborate', ja: '凝った'},
        {en: 'decent', ja: '満足できる'},
    ];
    ///////////////////////////////////////////////////////////////
    

    ///初期値///

//    const min = parseInt($('#min').val(),10);
//    const max = parseInt($('#max').val(),10)+1;
//    var random = unitSet(min,max);



    $('#min').val(1);
    $('#max').val(Math.ceil(words.length /10));

    var min = (eval($('#min').val())-1)*10;
    var max = eval($('#max').val())*10-1;
    var minUnit = $('#min').val();
    var maxUnit = $('#max').val();
    $('h1').text(`Unit${minUnit}〜Unit${maxUnit}`);

    function unitSet(){
        return Math.floor(Math.random() * (max+1 - min) + min);
    }

    var rand = unitSet();


    $('#re').click(function(){
        min = (eval($('#min').val())-1)*10;
        max = eval($('#max').val())*10-1;
        minUnit = $('#min').val();
        maxUnit = $('#max').val();
        $('h1').text(`Unit${minUnit}〜Unit${maxUnit}`);

        rand = unitSet();

        if($('#mode').hasClass('en-to-ja')){
            eSet();
        }else{
            jSet();
        }
        $('.unit-modal-wrapper').css('display','none');
    });

    function eSet(){
        rand = unitSet();
        $('#card-front').text(words[rand].en);
        $('#card-back').text(words[rand].ja);  
    }
   eSet();

    function jSet(){
        rand = unitSet();
        $('#card-front').text(words[rand].ja);
        $('#card-back').text(words[rand].en);
    }


    //切り替え
    $('#mode').click(function(){
        
        if($('#mode').hasClass("en-to-ja")){
            $('#mode').removeClass("en-to-ja");
            $('#mode').text("日本語→英語");
            $('#card-front').text(words[rand].ja);
            $('#card-back').text(words[rand].en); 
            
        } else{
            $('#mode').addClass("en-to-ja");
            $('#mode').text("英語→日本語");
            $('#card-front').text(words[rand].en);
            $('#card-back').text(words[rand].ja);
        }        
    });

    ///カード裏返し///
    function flip(){
        if($('#card').hasClass("open")){
            $('#card').removeClass("open");
        } else{
            $('#card').addClass("open");
        }
    }
    $('#card').click(flip);

    
    ///次のカード///
    $('#btn').click(function(){

        ///英語→日本語
        if($('#mode').hasClass('en-to-ja')){
            enToJa();

        ///日本語→英語
        }else{
            jaToEn();
        }
    });    


    ///日本語→英語めくり
    function jaToEn(){
        if($('#card').hasClass('open')){
            $('#card').removeClass('open').delay(600).queue(function(next){
                jSet();
                next();
            });
        }else{
            jSet();
        }
    }


    ///英語→日本語めくり
    function enToJa(){
        if($('#card').hasClass('open')){
            $('#card').removeClass('open').delay(600).queue(function(next){
                eSet();
                next();
            });
        }else{
            eSet();
        }
    }
    

});
